alias gs="git status"
alias gp="git push"
alias gpl="git pull"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gaa="git add ."
alias wip="git add . && git commit -m 'wip'"
alias gcm="git commit -m"

alias art="php artisan"